services:
  mysql:
    image: mysql:8.0
    container_name: qtmdashboard-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dago
      MYSQL_DATABASE: qtmdashboard${APP_KEYCLOAK_REALM_CODE}
    ports:
      - "3307:3306"
    volumes:
      - qtmdashboard-mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -pdago --silent"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s
    networks:
      - qtm-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qtmdashboard-backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      QTMDB_ENV: collaudo
      SERVER_CONNECTION_TIMEOUT: 900s
      SPRING_MVC_ASYNC_REQUEST_TIMEOUT: 900000
      QTM_HTTP_CLIENT_CONNECT_TIMEOUT: 60s
      QTM_HTTP_CLIENT_READ_TIMEOUT: 900s
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/qtmdashboard${APP_KEYCLOAK_REALM_CODE}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: dago
      QTM_OTP_TWILIO_ENABLED: ${QTM_OTP_TWILIO_ENABLED:-true}
      QTM_OTP_TWILIO_BASE_URL: ${QTM_OTP_TWILIO_BASE_URL:-https://verify.twilio.com/v2}
      QTM_OTP_TWILIO_SERVICE_SID: ${QTM_OTP_TWILIO_SERVICE_SID:-}
      QTM_OTP_TWILIO_ACCOUNT_SID: ${QTM_OTP_TWILIO_ACCOUNT_SID:-}
      QTM_OTP_TWILIO_AUTH_TOKEN: ${QTM_OTP_TWILIO_AUTH_TOKEN:-}
      QTM_OTP_TWILIO_API_KEY: ${QTM_OTP_TWILIO_API_KEY:-}
      QTM_OTP_TWILIO_API_SECRET: ${QTM_OTP_TWILIO_API_SECRET:-}
      QTM_OTP_TWILIO_DEFAULT_CHANNEL: ${QTM_OTP_TWILIO_DEFAULT_CHANNEL:-sms}
      APP_KEYCLOAK_SERVER_URL: http://keycloak:8080
      APP_KEYCLOAK_TOKEN_URL: http://keycloak:8080/realms/${APP_KEYCLOAK_REALM_CODE}/protocol/openid-connect/token
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://localhost:8085/realms/${APP_KEYCLOAK_REALM_CODE}
      APP_CORS_ALLOWED_ORIGINS: http://localhost:4200,http://127.0.0.1:4200
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/${APP_KEYCLOAK_REALM_CODE}/protocol/openid-connect/certs
    ports:
      - "8086:8086"
    networks:
      - qtm-network
      - keycloak-net
    extra_hosts:
     - "localhost:host-gateway"

networks:
  qtm-network:
    driver: bridge
  keycloak-net:
    external: true
    name: keycloak-docker_default

volumes:
  qtmdashboard-mysql-data:
    driver: local
